# Generated by Django 3.2.4 on 2021-08-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fruits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(verbose_name='No.')),
                ('name', models.CharField(max_length=255, verbose_name='果物名')),
                ('memo', models.TextField(verbose_name='メモ')),
            ],
        ),
    ]
